apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: letsencrypt
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - letsencrypt
  verbs:
  - get
  - update
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: letsencrypt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: letsencrypt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: letsencrypt
subjects:
- kind: ServiceAccount
  name: letsencrypt
  namespace: default
